ALTER TABLE blogs ENGINE=INNODB;
ALTER TABLE comics ENGINE=INNODB;
ALTER TABLE podcasts ENGINE=INNODB;
ALTER TABLE ratings ENGINE=INNODB;
ALTER TABLE users ENGINE=INNODB;

ALTER TABLE users MODIFY user_id INTEGER;
ALTER TABLE blogs MODIFY user_id INTEGER;

ALTER TABLE blogs ADD CONSTRAINT blogs_user_id_fk FOREIGN KEY (user_id) REFERENCES users (user_id);
